import React from 'react';
import Container from '../components/container/container';
import { Link } from 'react-router-dom';

export default function Terms() {
  return (
    <div className="min-h-screen bg-[#0f172a] text-slate-200">
      <Container>
        {/* Header */}
        <div className="text-center py-12 px-4">
          <h1 className="text-3xl md:text-4xl font-bold text-white mb-4">
            Terms & Conditions
          </h1>
          <p className="text-slate-400 max-w-2xl mx-auto">
            Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
          </p>
        </div>

        {/* Content Container */}
        <div className="max-w-4xl mx-auto px-4 pb-12">
          <div className="bg-slate-800/50 backdrop-blur-sm rounded-2xl border border-slate-700/50 p-8 md:p-12">
            
            {/* Scrollable Content Area */}
            <div className="max-h-[80vh] overflow-y-auto pr-4 space-y-8 custom-scrollbar">
              
              {/* 1. Introduction */}
              <section className="space-y-4">
                <h2 className="text-2xl font-bold text-white border-b border-slate-700 pb-2">
                  1. Introduction
                </h2>
                <div className="text-slate-300 space-y-3 leading-relaxed">
                  <p>
                    Welcome to Blogger.ai, an AI-powered content creation platform designed to help users generate high-quality blog content efficiently. 
                    These Terms & Conditions govern your use of our services and outline the rights and responsibilities of both users and Blogger.ai.
                  </p>
                  <p>
                    By accessing or using Blogger.ai, you agree to be bound by these terms. If you disagree with any part of these terms, 
                    please do not use our service. We reserve the right to modify these terms at any time, and such modifications will be effective 
                    immediately upon posting.
                  </p>
                </div>
              </section>

              {/* 2. User Accounts */}
              <section className="space-y-4">
                <h2 className="text-2xl font-bold text-white border-b border-slate-700 pb-2">
                  2. User Accounts
                </h2>
                <div className="text-slate-300 space-y-3 leading-relaxed">
                  <p>
                    <strong className="text-white">2.1 Account Creation:</strong> To access certain features of Blogger.ai, you must create an account. 
                    You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.
                  </p>
                  <p>
                    <strong className="text-white">2.2 Account Information:</strong> You must provide accurate, current, and complete information when creating an account. 
                    You agree to update this information to keep it accurate, current, and complete.
                  </p>
                  <p>
                    <strong className="text-white">2.3 Account Security:</strong> You are solely responsible for maintaining the security of your account. 
                    Blogger.ai is not liable for any loss or damage arising from unauthorized access to your account.
                  </p>
                  <p>
                    <strong className="text-white">2.4 Account Termination:</strong> We reserve the right to suspend or terminate your account at our discretion 
                    for violations of these terms or for any other reason we deem appropriate.
                  </p>
                </div>
              </section>

              {/* 3. Content Ownership */}
              <section className="space-y-4">
                <h2 className="text-2xl font-bold text-white border-b border-slate-700 pb-2">
                  3. Content Ownership
                </h2>
                <div className="text-slate-300 space-y-3 leading-relaxed">
                  <p>
                    <strong className="text-white">3.1 User Content:</strong> You retain ownership of all content you create using Blogger.ai. 
                    However, by using our service, you grant us a limited, non-exclusive, royalty-free license to use, store, and process your content 
                    solely for the purpose of providing our services.
                  </p>
                  <p>
                    <strong className="text-white">3.2 AI-Generated Content:</strong> Content generated by our AI algorithms is provided to you for your use. 
                    While you own the final output, you acknowledge that such content may incorporate patterns and information learned from various sources.
                  </p>
                  <p>
                    <strong className="text-white">3.3 Content Responsibility:</strong> You are solely responsible for all content you create, publish, or distribute 
                    using Blogger.ai, including ensuring compliance with applicable laws and regulations.
                  </p>
                  <p>
                    <strong className="text-white">3.4 Content Removal:</strong> We reserve the right to remove or disable access to content that violates 
                    these terms or applicable laws, without prior notice.
                  </p>
                </div>
              </section>

              {/* 4. AI Disclaimer */}
              <section className="space-y-4">
                <h2 className="text-2xl font-bold text-white border-b border-slate-700 pb-2">
                  4. AI Disclaimer
                </h2>
                <div className="text-slate-300 space-y-3 leading-relaxed">
                  <p>
                    <strong className="text-white">4.1 AI Limitations:</strong> Blogger.ai uses artificial intelligence to assist in content creation. 
                    AI-generated content may contain inaccuracies, biases, or errors. You are responsible for reviewing, editing, and fact-checking 
                    all content before publication.
                  </p>
                  <p>
                    <strong className="text-white">4.2 No Professional Advice:</strong> Content generated by Blogger.ai should not be considered professional, 
                    legal, medical, financial, or other expert advice. Always consult appropriate professionals for specific guidance.
                  </p>
                  <p>
                    <strong className="text-white">4.3 Continuous Improvement:</strong> Our AI models are continuously learning and evolving. 
                    The quality and nature of generated content may change over time as we improve our algorithms.
                  </p>
                  <p>
                    <strong className="text-white">4.4 Data Privacy:</strong> We are committed to protecting your data privacy. Please refer to our 
                    Privacy Policy for detailed information about how we handle your data.
                  </p>
                </div>
              </section>

              {/* 5. Prohibited Activities */}
              <section className="space-y-4">
                <h2 className="text-2xl font-bold text-white border-b border-slate-700 pb-2">
                  5. Prohibited Activities
                </h2>
                <div className="text-slate-300 space-y-3 leading-relaxed">
                  <p>
                    You agree not to use Blogger.ai for any of the following prohibited activities:
                  </p>
                  <ul className="list-disc list-inside space-y-2 ml-4">
                    <li>Creating content that is illegal, harmful, threatening, abusive, defamatory, or otherwise objectionable</li>
                    <li>Generating content that violates intellectual property rights of others</li>
                    <li>Using the service for fraudulent or deceptive purposes</li>
                    <li>Attempting to reverse engineer, copy, or distribute our AI algorithms or technology</li>
                    <li>Interfering with or disrupting the service or servers connected to the service</li>
                    <li>Using automated tools to access the service without prior authorization</li>
                    <li>Violating any applicable laws or regulations</li>
                    <li>Creating spam, malware, or other malicious content</li>
                    <li>Impersonating any person or entity</li>
                    <li>Using the service to harass, abuse, or harm others</li>
                  </ul>
                </div>
              </section>

              {/* 6. Limitation of Liability */}
              <section className="space-y-4">
                <h2 className="text-2xl font-bold text-white border-b border-slate-700 pb-2">
                  6. Limitation of Liability
                </h2>
                <div className="text-slate-300 space-y-3 leading-relaxed">
                  <p>
                    <strong className="text-white">6.1 Service As Is:</strong> Blogger.ai is provided "as is" without warranties of any kind, 
                    whether express or implied. We do not guarantee uninterrupted or error-free operation of the service.
                  </p>
                  <p>
                    <strong className="text-white">6.2 Limitation of Damages:</strong> To the maximum extent permitted by law, Blogger.ai 
                    shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the service.
                  </p>
                  <p>
                    <strong className="text-white">6.3 Maximum Liability:</strong> Our total liability for any claims related to the service 
                    shall not exceed the amount you paid for the service in the three months preceding the claim.
                  </p>
                  <p>
                    <strong className="text-white">6.4 Indemnification:</strong> You agree to indemnify and hold Blogger.ai harmless from 
                    any claims, damages, or expenses arising from your use of the service or violation of these terms.
                  </p>
                </div>
              </section>

              {/* Additional Sections */}
              <section className="space-y-4">
                <h2 className="text-2xl font-bold text-white border-b border-slate-700 pb-2">
                  7. Privacy and Data Protection
                </h2>
                <div className="text-slate-300 space-y-3 leading-relaxed">
                  <p>
                    Your privacy is important to us. Our collection and use of personal information is governed by our Privacy Policy, 
                    which is incorporated into these terms by reference. By using Blogger.ai, you consent to the collection and use of 
                    your information as described in our Privacy Policy.
                  </p>
                </div>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-bold text-white border-b border-slate-700 pb-2">
                  8. Termination
                </h2>
                <div className="text-slate-300 space-y-3 leading-relaxed">
                  <p>
                    We may terminate or suspend your account and bar access to the service immediately, without prior notice or liability, 
                    under our sole discretion, for any reason whatsoever and without limitation.
                  </p>
                </div>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-bold text-white border-b border-slate-700 pb-2">
                  9. Governing Law
                </h2>
                <div className="text-slate-300 space-y-3 leading-relaxed">
                  <p>
                    These terms shall be interpreted and governed by the laws of the jurisdiction in which Blogger.ai operates, 
                    without regard to conflict of law provisions.
                  </p>
                </div>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-bold text-white border-b border-slate-700 pb-2">
                  10. Contact Information
                </h2>
                <div className="text-slate-300 space-y-3 leading-relaxed">
                  <p>
                    If you have any questions about these Terms & Conditions, please contact us at:
                  </p>
                  <div className="bg-slate-700/50 rounded-lg p-4 mt-4">
                    <p className="text-white">Email: vyashika715@gmail.com</p>
                    <p className="text-white">Platform: Blogger.ai</p>
                  </div>
                </div>
              </section>

            </div>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="text-center py-8 space-y-4">
          <p className="text-slate-400 text-sm">
            By using Blogger.ai, you acknowledge that you have read and agree to these Terms & Conditions.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link 
              to="/"
              className="inline-flex items-center px-6 py-3 bg-slate-700 hover:bg-slate-600 text-white font-semibold rounded-lg transition-all duration-200"
            >
              ← Back to Home
            </Link>
            <Link 
              to="/privacy"
              className="inline-flex items-center px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-lg transition-all duration-200"
            >
              View Privacy Policy
            </Link>
          </div>
        </div>
      </Container>

      {/* Custom Scrollbar Styles */}
      <style jsx>{`
        .custom-scrollbar::-webkit-scrollbar {
          width: 8px;
        }
        .custom-scrollbar::-webkit-scrollbar-track {
          background: #1e293b;
          border-radius: 4px;
        }
        .custom-scrollbar::-webkit-scrollbar-thumb {
          background: #475569;
          border-radius: 4px;
        }
        .custom-scrollbar::-webkit-scrollbar-thumb:hover {
          background: #64748b;
        }
      `}</style>
    </div>
  );
}
